# Generated by Django 4.1.3 on 2023-05-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='v_key',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='admins',
            name='v_status',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
